baseURL = "https://www.etsijamais.fr/"
languageCode = "fr"
title = "Et si jamais"
theme = "PaperMod"
enableRobotsTXT = true

[params]
defaultTheme = "auto"
description = "Coaching Agile, Coaching Professionnel, Numérique Responsable & Écoconception, avec un regard systémique."
assets = { disableHLJS = false }
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableThemeToggle = false
customCSS = ["css/custom.css"]

[params.homeInfoParams]
Title = "Et si jamais"
Content = "Coaching Agile, Coaching Professionnel, Numérique Responsable & Écoconception, avec un regard systémique."

[[menu.main]]
name = "Services"
url = "/services/"
weight = 10

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 20

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 30

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
